// This file is automatically generated but modified to use singleton instance.
import { supabase } from "@/lib/supabase";

// Re-export the singleton instance
export { supabase } from "@/lib/supabase";

// Legacy export for backward compatibility
export default supabase;
