// This file is automatically generated but modified to avoid embedding secrets.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Load Supabase config from environment variables. For Vite, set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Warn in development — the build should inject these via Vite.
  // Do not throw here to keep server-side scripts or tests editable; scripts should check envs when run.
  // If keys were previously committed, rotate them in your Supabase project immediately.
  // eslint-disable-next-line no-console
  console.warn(
    "Supabase config missing: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment."
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
