name: Generate a build and push to another branch

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # garante que o job possa fazer push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Debug build output
        run: |
          pwd
          ls -la
          echo "---- dist ----"
          ls -la dist

      - name: Push dist/ to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist              # branch de destino (será criada se não existir)
          FOLDER: dist              # pasta gerada pelo Vite
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "dist: ({sha}) {msg}"
